name: build-images 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 3 * * FRI'

jobs:
  compiler-images:
    continue-on-error: ${{ matrix.config.continue-on-error == 'true' }}
    strategy:
      matrix:
        include:
          - DOCKERFILE: 'ubuntu'
            OS: 'ubuntu:24.04'
            COMPILER_VERSION: 'minimal'
          - DOCKERFILE: 'gcc'
            OS: 'ubuntu:24.04'
            COMPILER_VERSION: 11
          - DOCKERFILE: 'gcc'
            OS: 'ubuntu:24.04'
            COMPILER_VERSION: 12
          - DOCKERFILE: 'gcc'
            OS: 'ubuntu:24.04'
            COMPILER_VERSION: 13
          - DOCKERFILE: 'gcc'
            OS: 'ubuntu:24.04'
            COMPILER_VERSION: 14
          - DOCKERFILE: 'gcc'
            OS: 'ubuntu:25.10'
            COMPILER_VERSION: 15
          - DOCKERFILE: 'clang'
            OS: 'ubuntu:22.04'
            COMPILER_VERSION: 13
          - DOCKERFILE: 'clang'
            OS: 'ubuntu:22.04'
            COMPILER_VERSION: 14
          - DOCKERFILE: 'clang'
            OS: 'ubuntu:22.04'
            COMPILER_VERSION: 15
          - DOCKERFILE: 'clang'
            OS: 'ubuntu:22.04'
            COMPILER_VERSION: 16
          - DOCKERFILE: 'clang'
            OS: 'ubuntu:24.04'
            COMPILER_VERSION: 17
          - DOCKERFILE: 'clang'
            OS: 'ubuntu:24.04'
            COMPILER_VERSION: 18
          - DOCKERFILE: 'clang'
            OS: 'ubuntu:25.10'
            COMPILER_VERSION: 19
          - DOCKERFILE: 'clang'
            OS: 'ubuntu:25.10'
            COMPILER_VERSION: 20
          - DOCKERFILE: 'clang'
            OS: 'ubuntu:25.10'
            COMPILER_VERSION: 21
          - DOCKERFILE: 'nvcc'
            OS: 'nvidia/cuda:12.6.1-devel-ubuntu24.04'
            COMPILER_VERSION: 12.6
            
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ matrix.DOCKERFILE }} 
          tags: xzzx/devel:${{ matrix.DOCKERFILE }}-${{ matrix.COMPILER_VERSION }}
          push: true
          build-args: |
            DOCKERFILE=${{ matrix.DOCKERFILE }}
            OS=${{ matrix.OS }}
            COMPILER_VERSION=${{ matrix.COMPILER_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
