name: build-images 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 3 * * FRI'

jobs:
  ubuntu-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          file: ubuntu 
          tags: xzzx/devel:ubuntu
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  compiler-images:
    needs: ubuntu-image
    continue-on-error: ${{ matrix.config.continue-on-error == 'true' }}
    strategy:
      matrix:
        dockerfile: ['gcc', 'clang', 'icx']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          file: ${{ matrix.dockerfile }} 
          tags: xzzx/devel:${{ matrix.dockerfile }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
